### ISSUE TITLE
Tabs oben schlecht lesbar

### ISSUE THREAD

**Issue by TEbinger** [mmmsued/hilfe#2]
Leider können die Tabs bei entsprechendem Hintergrund nur schlecht gelesen werden. Kann man die weniger transparent gestalten?

**Comment by mmmsued** [comment]
Laut Minetest Api kann man die Transparenz auf true oder false setzen. Ich habe beides probiert, es hatte aber keinen Effekt ...

**Comment by TEbinger** [comment]
Vielleicht hat @EliasFleckenstein eine Idee?

**Comment by mmmsued** [comment]
In den einschlägigen Foren wird das Thema diskutiert. Einhellige Meinung: Es ist ein Fehler in der Implementierung der Formspecs. Das Argument transparent gibt es zwar, aber es wird gar nicht unterstützt. Allen hoffen, dass der Fehler in einer zukünftigen Version behoben wird.

**Comment by mmmsued** [comment]
Problem gelöst. Die Tabs wurden um 0.7 nach unten gesetzt. Dadurch liegen sie auf dem Hintergrund des Formspecs. Das finde ich zwar optisch nicht so schön wie die außerhalb des Formspecs angebrachten Tabs, aber die Lesbarkeit ist jetzt gewährleistet.
